//! Catching `dump()` and `dd()` out of the response.
//!
//! ## The item's cost estimate was wrong twice
//!
//! P3-18 was rated expensive on the grounds that it "needs a collector service
//! and a Composer package". Checked against real projects, neither half holds
//! for Laravel:
//!
//! * **The Composer package already ships.** `symfony/var-dumper` is a
//!   `laravel/framework` dependency — present in every checkout here that has a
//!   `vendor/` at all.
//! * **The collector already ships too.** `vendor/bin/var-dump-server` comes
//!   with it.
//!
//! What is *actually* expensive is the thing that looks obvious: writing the
//! collector. `VAR_DUMPER_FORMAT=server` sends
//! `base64(serialize([Data, context]))` over a socket — a PHP object graph.
//! Reading it in Rust means a `serialize()` parser **plus** Symfony's internal
//! `Cloner\Data` representation, where a nested value is an indirection into a
//! per-depth slot table and every object is a `Stub`. That is a large amount of
//! code sitting on an internal that Symfony is free to change, and the failure
//! mode when it does is a dump viewer that renders nonsense.
//!
//! So the collector is not written. Symfony's own runs inside the project
//! container and **renders the dumps itself**; this app streams the text.
//! Nothing here parses Symfony's internals, so nothing here can break when they
//! move.
//!
//! ## No toggle, because there is nothing to toggle
//!
//! The overlay sets the two environment variables for every eligible project
//! and leaves them set. That is safe, and it was verified rather than assumed:
//! with the variables set and **nothing listening**, `dump()` renders into the
//! response exactly as it does today — `ServerDumper` falls back. So the
//! variables cost nothing when the catcher is closed, and a state file for a
//! setting with no observable off-state would be ceremony.
//!
//! Two things had to be true for this to reach a *web* request rather than only
//! the CLI, and both were checked in a running container: the official PHP
//! image's `docker.conf` sets `clear_env = no`, so the container environment
//! reaches FPM workers, and `variables_order` is `EGPCS` — the `E` is what puts
//! it in `$_SERVER`, which is where `VarDumper` looks.

use crate::error::{Code, Error, Result};
use serde::Serialize;
use std::path::{Path, PathBuf};

/// Where the collector listens, inside the container.
///
/// Loopback, not `0.0.0.0`: the server and the application are the same
/// container, and a dump stream is application data that has no reason to be
/// reachable from the network.
pub const HOST: &str = "127.0.0.1";

/// Symfony's own default, kept so a project that already configured this by
/// hand keeps working.
pub const PORT: u16 = 9912;

/// The collector, relative to the project root.
pub const BINARY: &str = "vendor/bin/var-dump-server";

pub fn overlay_path(root: &Path) -> PathBuf {
    root.join("generated").join("docker-compose.dumps.yml")
}

pub fn server_address() -> String {
    format!("{HOST}:{PORT}")
}

#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct Status {
    /// False when the project has no `vendor/bin/var-dump-server` — usually a
    /// checkout whose dependencies have never been installed.
    pub available: bool,
    /// False for node projects and for a project the overlay has not reached
    /// yet, which is the difference between "cannot" and "not until you
    /// restart it".
    pub configured: bool,
    pub binary: String,
    pub address: String,
    /// Named so the UI can say what to run, rather than implying this app is
    /// the only way to produce a dump.
    pub runtime: String,
}

/// One project's worth of overlay input.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Entry {
    pub service: String,
}

// -------------------------------------------------------------- pure logic

/// Render the overlay, or None when no project is eligible.
pub fn overlay_yaml(entries: &[Entry]) -> Option<String> {
    if entries.is_empty() {
        return None;
    }

    let mut out = String::from(
        "# Generated by StackVo Desktop — do not edit.\n\
         #\n\
         # Points Symfony's VarDumper at a collector inside the same container.\n\
         # Harmless when nothing is listening: dump() falls back to rendering\n\
         # into the response, which is what it does without these variables.\n\
         #\n\
         # NOTE: `stackvo up` from the Bash CLI does not layer this file.\n\
         services:\n",
    );

    let mut sorted: Vec<&Entry> = entries.iter().collect();
    sorted.sort_by(|a, b| a.service.cmp(&b.service));

    for entry in sorted {
        out.push_str(&format!("  {}:\n", entry.service));
        out.push_str("    environment:\n");
        out.push_str("      VAR_DUMPER_FORMAT: \"server\"\n");
        out.push_str(&format!(
            "      VAR_DUMPER_SERVER: \"{}\"\n",
            server_address()
        ));
    }

    Some(out)
}

/// The argv that starts the collector inside a container.
///
/// `-i` without `-t`: the process is driven by this app, not by a person, and
/// asking for a TTY that nothing is attached to is how `docker exec` fails with
/// a message about the input device.
pub fn server_argv(container: &str) -> Vec<String> {
    vec![
        "exec".to_string(),
        "-w".to_string(),
        crate::xdebug::CONTAINER_PATH.to_string(),
        container.to_string(),
        "php".to_string(),
        BINARY.to_string(),
        "--host".to_string(),
        format!("tcp://{}", server_address()),
    ]
}

/// Is this a line worth showing?
///
/// The server opens with a banner — a title, an underline, an "[OK] listening"
/// box and a hint about Ctrl-C — none of which is a dump and all of which would
/// be the first thing in a pane whose whole job is to show dumps.
pub fn is_banner(line: &str) -> bool {
    let t = line.trim();
    t.is_empty()
        || t == "Symfony Var Dumper Server"
        || t.chars().all(|c| c == '=')
        || t.starts_with("[OK]")
        || t.starts_with("// Quit the server")
}

// ------------------------------------------------------------------- I/O

/// Every PHP project the generator emitted **and** whose vendor tree has the
/// collector.
///
/// The second condition is not caution for its own sake: setting the variables
/// for a project with no var-dumper points it at a server it can never reach,
/// and while the fallback keeps that harmless, the status pane would then claim
/// a capability that does not exist.
fn entries(root: &Path) -> Vec<Entry> {
    let mut out = Vec::new();

    let generated =
        std::fs::read_to_string(root.join("generated").join("docker-compose.projects.yml"))
            .unwrap_or_default();
    let services = crate::xdebug::generated_services(&generated);

    let Ok(dirs) = std::fs::read_dir(root.join("projects")) else {
        return out;
    };

    for dir in dirs.flatten() {
        let path = dir.path();
        let Some(name) = path.file_name().and_then(|n| n.to_str()) else {
            continue;
        };
        if !path.is_dir() || !services.iter().any(|s| s == name) {
            continue;
        }
        if !path.join(BINARY).is_file() {
            continue;
        }
        let Ok(manifest) = crate::manifest::read(&path.join("stackvo.json"), name) else {
            continue;
        };
        if manifest.runtime != "php" {
            continue;
        }

        out.push(Entry {
            service: name.to_string(),
        });
    }

    out
}

/// Re-render the overlay, and report whether it now exists.
pub fn sync(root: &Path) -> bool {
    let path = overlay_path(root);

    match overlay_yaml(&entries(root)) {
        Some(yaml) => {
            if let Some(parent) = path.parent() {
                if std::fs::create_dir_all(parent).is_err() {
                    return false;
                }
            }
            match crate::atomic::write(&path, &yaml) {
                Ok(()) => true,
                Err(e) => {
                    tracing::warn!(path = %path.display(), error = %e, "could not write the dumps overlay");
                    let _ = std::fs::remove_file(&path);
                    false
                }
            }
        }
        None => {
            let _ = std::fs::remove_file(&path);
            false
        }
    }
}

/// What this project can do, and whether the running container knows about it.
pub async fn status(root: &Path, name: &str) -> Result<Status> {
    let dir = crate::workspace::project_dir(root, name)?;
    let manifest_file = dir.join("stackvo.json");
    if !manifest_file.is_file() {
        return Err(Error::not_found(format!("project {name}")));
    }
    let manifest = crate::manifest::read(&manifest_file, name)?;

    // Read from the running container, never inferred: `stackvo up` from the
    // Bash CLI layers three compose files, not seven, and will recreate the
    // container without these variables.
    let configured = crate::engine::inspect(name)
        .await
        .map(|d| {
            d.env
                .iter()
                .any(|v| v.starts_with("VAR_DUMPER_FORMAT=server"))
        })
        .unwrap_or(false);

    Ok(Status {
        available: manifest.runtime == "php" && dir.join(BINARY).is_file(),
        configured,
        binary: BINARY.to_string(),
        address: server_address(),
        runtime: manifest.runtime,
    })
}

/// Stop any collector running in this container.
///
/// **Killing `docker exec` does not kill what it exec'd.** The client goes
/// away, the PHP process inside the container keeps the port. Found by the
/// integration test failing its second run with Symfony's own
/// `stream_socket_server(): Address already in use` — the first run's collector
/// was still holding 9912.
///
/// Called on close *and* before starting, so a collector left behind by a crash
/// or by a `docker exec` that died with the app does not block the next
/// attempt. Self-healing beats depending on a clean shutdown that cannot be
/// guaranteed.
pub async fn stop(container: &str) {
    let _ = tokio::process::Command::new("docker")
        .args(["exec", container, "pkill", "-f", "var-dump-server"])
        .output()
        .await;
}

/// Start the collector and hand back its argv, refusing a project that cannot
/// run one.
pub async fn prepare(root: &Path, name: &str) -> Result<Vec<String>> {
    let status = status(root, name).await?;

    if !status.available {
        return Err(Error::new(
            Code::Unsupported,
            format!("{name} has no {BINARY}"),
        )
        .with_hint(
            "It ships with symfony/var-dumper, which Laravel depends on — run `composer install`.",
        ));
    }

    let running = crate::engine::inspect(name)
        .await
        .map(|d| d.running)
        .unwrap_or(false);
    if !running {
        return Err(
            Error::new(Code::Conflict, format!("{name} is not running")).with_hint(
                "The collector runs inside the project's container. Start the project first.",
            ),
        );
    }

    let container = crate::engine::container_name(name);
    // Clear a stale one before binding, or Symfony refuses the port.
    stop(&container).await;
    Ok(server_argv(&container))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_overlay_points_var_dumper_at_the_container_itself() {
        let yaml = overlay_yaml(&[Entry {
            service: "shop".into(),
        }])
        .unwrap();

        assert!(yaml.contains("  shop:\n"));
        assert!(yaml.contains("VAR_DUMPER_FORMAT: \"server\""), "{yaml}");
        // Loopback: the collector and the application are the same container,
        // and dumps are application data with no reason to be on the network.
        assert!(
            yaml.contains("VAR_DUMPER_SERVER: \"127.0.0.1:9912\""),
            "{yaml}"
        );
    }

    /// Symfony's own default. A project that configured this by hand keeps
    /// working rather than being pointed somewhere new.
    #[test]
    fn the_port_is_the_one_symfony_already_uses() {
        assert_eq!(PORT, 9912);
    }

    #[test]
    fn an_empty_overlay_is_no_overlay() {
        assert!(overlay_yaml(&[]).is_none());
    }

    #[test]
    fn projects_are_rendered_in_a_stable_order() {
        let yaml = overlay_yaml(&[
            Entry {
                service: "zebra".into(),
            },
            Entry {
                service: "apple".into(),
            },
        ])
        .unwrap();
        assert!(yaml.find("  apple:").unwrap() < yaml.find("  zebra:").unwrap());
    }

    /// The server's opening banner is four lines of furniture. In a pane whose
    /// whole job is to show dumps it would be the first thing on screen and the
    /// only thing there until somebody dumped something.
    #[test]
    fn the_startup_banner_is_not_mistaken_for_output() {
        for line in [
            "Symfony Var Dumper Server",
            "=========================",
            " [OK] Server listening on tcp://127.0.0.1:9912",
            " // Quit the server with CONTROL-C.",
            "",
            "   ",
        ] {
            assert!(is_banner(line), "{line:?} should be filtered");
        }

        // And a real dump is not.
        for line in [
            "array:2 [",
            "  \"user\" => array:2 [",
            "$ Standard input code",
            "  date     Thu, 30 Jul 2026 09:43:37 +0000",
        ] {
            assert!(!is_banner(line), "{line:?} should be shown");
        }
    }

    /// `-t` asks for a TTY. Nothing is attached to this one — it is driven by
    /// the app — and `docker exec -t` without one fails on the input device.
    #[test]
    fn the_collector_is_started_without_a_tty() {
        let argv = server_argv("stackvo-shop");

        assert_eq!(argv[0], "exec");
        assert!(!argv.iter().any(|a| a == "-t" || a == "-it"));
        assert!(argv.contains(&"vendor/bin/var-dump-server".to_string()));
        assert!(argv.contains(&"tcp://127.0.0.1:9912".to_string()));
        // Run from the application root, or the relative vendor path misses.
        assert_eq!(argv[1], "-w");
        assert_eq!(argv[2], "/var/www/html");
    }

    /// Argv, never a shell string.
    #[test]
    fn a_hostile_container_name_is_one_argument() {
        let argv = server_argv("stackvo-a; rm -rf ~");
        assert!(argv.contains(&"stackvo-a; rm -rf ~".to_string()));
        assert!(!argv.iter().any(|a| a == "sh" || a == "-c"));
    }
}
